datasets:
  cc3m:
    data_type: images
    #build_info:
    size_img: 224
    img_transform: ["img_rand_crop"]
    size_frame: 1
    dataset: cc3m
    split: train
    data_dir: '/content/drive/MyDrive/_pretrain'
    part: 1 #[0,1,2,3,4,5,6,7,8,9]
